default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123456
  port: 5432
  pool: 15

development:
  <<: *default
  database: portalc3
test:
  <<: *default
  database: Projeto_test

production:
  <<: *default
  database: portalc3
  username: postgres
  password: 123456
